server:
  port: 10003

spring:
  application:
    name: prompt-example
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
#  nacos:
#    config:
#      enabled: true
#      server-addr: localhost:8848